#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL_gfx
Version  : 2.0.25
Release  : 9
URL      : http://www.ferzkopp.net/Software/SDL_gfx-2.0/SDL_gfx-2.0.25.tar.gz
Source0  : http://www.ferzkopp.net/Software/SDL_gfx-2.0/SDL_gfx-2.0.25.tar.gz
Summary  : SDL graphics drawing primitives and other support functions
Group    : Development/Tools
License  : Zlib
Requires: SDL_gfx-lib
BuildRequires : SDL-dev
BuildRequires : SDL-dev32
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32ice)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)

%description
The SDL_gfx library evolved out of the SDL_gfxPrimitives code which
provided basic drawing routines such as lines, circles or polygons and
SDL_rotozoom which implemented a interpolating rotozoomer for SDL
surfaces.

The current components of the SDL_gfx library are:

   * Graphic Primitives (SDL_gfxPrimitves.h)
   * Rotozoomer (SDL_rotozoom.h)
   * Framerate control (SDL_framerate.h)
   * MMX image filters (SDL_imageFilter.h)
   * Custom blit functions (SDL_gfxBlitFunc.h)

The library is is written in plain C and can be used in C++ code.

%package dev
Summary: dev components for the SDL_gfx package.
Group: Development
Requires: SDL_gfx-lib
Provides: SDL_gfx-devel

%description dev
dev components for the SDL_gfx package.


%package dev32
Summary: dev32 components for the SDL_gfx package.
Group: Default
Requires: SDL_gfx-lib32
Requires: SDL_gfx-dev

%description dev32
dev32 components for the SDL_gfx package.


%package lib
Summary: lib components for the SDL_gfx package.
Group: Libraries

%description lib
lib components for the SDL_gfx package.


%package lib32
Summary: lib32 components for the SDL_gfx package.
Group: Default

%description lib32
lib32 components for the SDL_gfx package.


%prep
%setup -q -n SDL_gfx-2.0.25
pushd ..
cp -a SDL_gfx-2.0.25 build32
popd

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL/SDL_framerate.h
/usr/include/SDL/SDL_gfxBlitFunc.h
/usr/include/SDL/SDL_gfxPrimitives.h
/usr/include/SDL/SDL_gfxPrimitives_font.h
/usr/include/SDL/SDL_imageFilter.h
/usr/include/SDL/SDL_rotozoom.h
/usr/lib64/libSDL_gfx.so
/usr/lib64/pkgconfig/SDL_gfx.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libSDL_gfx.so
/usr/lib32/pkgconfig/32SDL_gfx.pc
/usr/lib32/pkgconfig/SDL_gfx.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL_gfx.so.15
/usr/lib64/libSDL_gfx.so.15.9.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libSDL_gfx.so.15
/usr/lib32/libSDL_gfx.so.15.9.1
