#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL_gfx
Version  : 2.0.26
Release  : 12
URL      : http://www.ferzkopp.net/Software/SDL_gfx-2.0/SDL_gfx-2.0.26.tar.gz
Source0  : http://www.ferzkopp.net/Software/SDL_gfx-2.0/SDL_gfx-2.0.26.tar.gz
Summary  : SDL graphics drawing primitives and other support functions
Group    : Development/Tools
License  : Zlib
Requires: SDL_gfx-lib = %{version}-%{release}
Requires: SDL_gfx-license = %{version}-%{release}
BuildRequires : SDL-dev
BuildRequires : SDL-dev32
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32ice)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)

%description
The SDL_gfx library evolved out of the SDL_gfxPrimitives code which
provided basic drawing routines such as lines, circles or polygons and
SDL_rotozoom which implemented a interpolating rotozoomer for SDL
surfaces.

The current components of the SDL_gfx library are:

   * Graphic Primitives (SDL_gfxPrimitives.h)
   * Rotozoomer (SDL_rotozoom.h)
   * Framerate control (SDL_framerate.h)
   * MMX image filters (SDL_imageFilter.h)
   * Custom blit functions (SDL_gfxBlitFunc.h)

The library is is written in plain C and can be used in C++ code.

%package dev
Summary: dev components for the SDL_gfx package.
Group: Development
Requires: SDL_gfx-lib = %{version}-%{release}
Provides: SDL_gfx-devel = %{version}-%{release}
Requires: SDL_gfx = %{version}-%{release}

%description dev
dev components for the SDL_gfx package.


%package dev32
Summary: dev32 components for the SDL_gfx package.
Group: Default
Requires: SDL_gfx-lib32 = %{version}-%{release}
Requires: SDL_gfx-dev = %{version}-%{release}

%description dev32
dev32 components for the SDL_gfx package.


%package lib
Summary: lib components for the SDL_gfx package.
Group: Libraries
Requires: SDL_gfx-license = %{version}-%{release}

%description lib
lib components for the SDL_gfx package.


%package lib32
Summary: lib32 components for the SDL_gfx package.
Group: Default
Requires: SDL_gfx-license = %{version}-%{release}

%description lib32
lib32 components for the SDL_gfx package.


%package license
Summary: license components for the SDL_gfx package.
Group: Default

%description license
license components for the SDL_gfx package.


%prep
%setup -q -n SDL_gfx-2.0.26
pushd ..
cp -a SDL_gfx-2.0.26 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570901815
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1570901815
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL_gfx
cp %{_builddir}/SDL_gfx-2.0.26/COPYING %{buildroot}/usr/share/package-licenses/SDL_gfx/636b8ece5da5c6058e06d24bbf69b3eae5f848a8
cp %{_builddir}/SDL_gfx-2.0.26/LICENSE %{buildroot}/usr/share/package-licenses/SDL_gfx/4e7f05fe9b8c0b7c0dc091c4fdbeb6eb84d7e141
cp %{_builddir}/SDL_gfx-2.0.26/Test/COPYING %{buildroot}/usr/share/package-licenses/SDL_gfx/da2588607d4def80129bbabaad75278a1a12e566
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL/SDL_framerate.h
/usr/include/SDL/SDL_gfxBlitFunc.h
/usr/include/SDL/SDL_gfxPrimitives.h
/usr/include/SDL/SDL_gfxPrimitives_font.h
/usr/include/SDL/SDL_imageFilter.h
/usr/include/SDL/SDL_rotozoom.h
/usr/lib64/libSDL_gfx.so
/usr/lib64/pkgconfig/SDL_gfx.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libSDL_gfx.so
/usr/lib32/pkgconfig/32SDL_gfx.pc
/usr/lib32/pkgconfig/SDL_gfx.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL_gfx.so.16
/usr/lib64/libSDL_gfx.so.16.9.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libSDL_gfx.so.16
/usr/lib32/libSDL_gfx.so.16.9.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL_gfx/4e7f05fe9b8c0b7c0dc091c4fdbeb6eb84d7e141
/usr/share/package-licenses/SDL_gfx/636b8ece5da5c6058e06d24bbf69b3eae5f848a8
/usr/share/package-licenses/SDL_gfx/da2588607d4def80129bbabaad75278a1a12e566
